### PR TITLE
Fix MapExtensions to work with root path #683

### PR DESCRIPTION
**Pull request by cnblogs-dudu**
See #683

### CODE REVIEW

**Comment by Tratcher** [comment]
What's the point of Map("/", ... ?

**Comment by cnblogs-dudu** [comment]
In my case, it's for redirecting.
```csharp
app.Map("/", _ =>
{
    _.Run((context) =>
    {
        context.Response.Redirect("/markdown/tohtml");
        return Task.FromResult(0);
    });
});
```
```csharp
public class MarkdownController : Controller
{
    [Route("markdown/tohtml")]
    public string ToHtml()
    {
    }
}
```

**Comment by PinpointTownes** [comment]
I agree with @Tratcher, I don't think this change makes much sense as the whole point of `Map` is to create "virtual directories".

You probably want to do something like that:

```csharp
app.Use((context, next) => {
    if (context.Request.Path == "/") {
        context.Response.Redirect("/markdown/tohtml");
        return Task.FromResult(0);
   }

   return next();
});
```

**Comment by Tratcher** [comment]
Map is a StartsWith check, not an Equals check. Everything StartsWith `/`, so there's no point in using it with Map. @PinpointTownes sample is your best option.

**Comment by cnblogs-dudu** [comment]
You are right. I missed the point of app.Map.

**Pull request closed without merging**
