### PR TITLE
AuthN cleanup

### PR DESCRIPTION
**Pull request by HaoK**
- Rename Security folder -> Authentication
- Change Authenticate to only take one scheme to match other APIs, the
params overload did not make it any cleaner to consume (since it didn't
produce a combined ClaimsPrincipal anyways)

cc @lodejard @Praburaj @Tratcher

### CODE REVIEW

**Comment by davidfowl** [comment]
Looks cleaner

**Comment by HaoK** [comment]
Merged 08ddbe853130fe10bdde6f8b529e5a885e0974be

**Comment by dougbu** [comment]
@HaoK this change appears to be incomplete.  the `AuthorizationPolicy` class still exposes a collection of schemes.  it doesn't look possible to fix the current build break in MVC where it's calling `HttpContext.AuthenticateAsync(Policy.ActiveAuthenticationSchemes)` without fixing that gap.  what do you recommend as a quick fix for MVC?

**Comment by HaoK** [comment]
I’ll fix it

**Pull request closed without merging**
