### PR TITLE
Adds null checks and fixes typo (#682)

### PR DESCRIPTION
**Pull request by jkotalik**
#682 
@Tratcher 
I can factor out some of the null checks into a separate method, however it seems inappropriate.

### CODE REVIEW

**Comment by jkotalik** [comment]
@Tratcher Seems to be an issue here for null checks: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/PathString.cs#L341
We assume that if both of them have no value, they are equal, which means that a null pathString and an empty path string are the same thing. Thoughts?

**Comment by davidfowl** [comment]
@jkotalik add some tests

**Comment by Tratcher** [comment]
Oh hay, Host/Path/Query/FragmentStrings are all structs. I guess those don't need null checks after all.

Side note: Put the bug number in the description (not the title) so it gets auto linked.

**Comment by Tratcher** [comment]
Note: delete your branch. Also, if your branch is up to date when you push to dev, then the PR is aromatically closed as Merged.

**Pull request closed without merging**
