### PR TITLE
Cache doesn't need clearing when resolving uncached feature

### PR DESCRIPTION
**Pull request by benaadams**
Otherwise there is no point in having a cache as it only works with one feature at a time

### CODE REVIEW

**Comment by lodejard** [comment]
:ok:

**Comment by davidfowl** [comment]
@lodejard did you?

**Comment by benaadams** [comment]
Rebased

**Comment by muratg** [comment]
@lodejard did you get a chance to look into this?

**Comment by benaadams** [comment]
rebased

**Comment by benaadams** [comment]
Build fails due to pause/break on linux
```
Installing Mono
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.ss4gX2Frn7 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
gpg: requesting key D3D831EF from hkp server keyserver.ubuntu.com
gpg: key D3D831EF: public key "Xamarin Public Jenkins (auto-signing) <releng@xamarin.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
3.93sW: Conflicting distribution: http://download.mono-project.com wheezy/snapshots/4.0.5 InRelease (expected wheezy/snapshots but got wheezy)
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Pull request merged**
