### PR TITLE
Target dnx451

### PR DESCRIPTION
**Pull request by bricelam**
This reverts a051244faffe99302dad919827261b79aa99e487 for DNX

### CODE REVIEW

**Comment by davidfowl** [comment]
Nah

**Comment by Eilon** [comment]
@davidfowl what's the issue?

**Comment by davidfowl** [comment]
Don't want DNX creeping into anything. We should just have an announcement telling people to add framework assemblies. The .NET CLI will handle the main cases for us.

**Comment by Eilon** [comment]
@davidfowl this is temporary until we get closer to having tooling available.

**Comment by bricelam** [comment]
Recalling. After chatting with @Eilon, we decided that adding the facades to user's `project.json` is an acceptable workaround.

**Pull request closed without merging**
