### PR TITLE
Incorporate StringSegment from primitives

### PR DESCRIPTION
**Pull request by rynowak**
/cc @Tratcher

### CODE REVIEW

**Comment by rynowak** [comment]
The code here: https://github.com/aspnet/HttpAbstractions/pull/434/files#diff-39dff6421a269d5f55533106f769fb40L188 will throw now if you try to access `Current` while in an invalid state. Is this a concern? This code is internal, so I expect that callers are calling `MoveNext()` properly.

**Comment by Tratcher** [comment]
Not too concerned until it breaks :-). :shipit:

**Comment by davidfowl** [comment]
:shipit:

**Comment by rynowak** [comment]
Feel free to merge this if you want, I'm in the desert :cactus: :camel: :cactus:

**Comment by davidfowl** [comment]
@rynowak plzmergekthxbye

**Pull request closed without merging**
