### PR TITLE
Set default path=/ when removing cookie

### PR DESCRIPTION
**Pull request by pakrym**
https://github.com/aspnet/HttpAbstractions/issues/437

/cc @Tratcher @JunTaoLuo @halter73

### CODE REVIEW

**Comment by halter73** [comment]
:shipit:

**Comment by davidfowl** [comment]
Weird we had that much logic that could be readily deleted :smile: /cc @Tratcher

**Comment by pakrym** [comment]
:up: :date:

**Comment by JunTaoLuo** [comment]
:shipit:

**Comment by davidfowl** [comment]
:shipit:

**Pull request merged**
