### PR TITLE
To de-dupe, we must remove (again)

### PR DESCRIPTION
**Pull request by dougbu**
- part of aspnet/Common#93
- use `WebEncoders` from Common repo
- leave some of `WebEncodersTests` to ensure resources are brought in correctly

### CODE REVIEW

**Comment by anurse** [comment]
:shipit: (once the package is available)

**Comment by pranavkm** [comment]
:shipit:

**Comment by pranavkm** [comment]
When checking this, could you do this in two passes (first check in the Common change followed by the 2 repo changes)?

**Comment by dougbu** [comment]
9a28932

**Pull request merged**
