### PR TITLE
Adds some security headers

### PR DESCRIPTION
**Pull request by joseftw**
Adds Referrer-Policy, X-Content-Type-Options, X-Frame-Options and X-XSS-Protection headers

### CODE REVIEW

**Comment by Tratcher** [comment]
Spec references?

**Comment by joseftw** [comment]
Referrer-Policy: https://www.w3.org/TR/referrer-policy/
X-Content-Type-Options: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
X-Frame-Options: https://www.w3.org/TR/UISecurity/
X-XSS-Protection: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

Sorry for some mozilla links but could not find any w3 links.

**Comment by Tratcher** [comment]
@blowdart

**Comment by Eilon** [comment]
@Tratcher / @blowdart - any further action planned on this PR?

**Comment by blowdart** [comment]
It could be useful, I have no strong feelings.

**Comment by Tratcher** [comment]
Yeah, it's not clear that adding only the header names is much value. If there were also APIs associated with these it would make more sense.

E.g. Referrer-Policy is not much use without it's list of possible values: "no-referrer" / "no-referrer-when-downgrade" / "strict-origin" / "strict-origin-when-cross-origin" / "same-origin" / "origin" / "origin-when-cross-origin" / "unsafe-url"
X-Content-Type-Options has only one defined value "nosniff".
X-Frame-Options and X-XSS-Protection both have some structure to them and you'd want some formatters.

**Comment by muratg** [comment]
We thank you for the contribution and look forward to collaborating more in the future.

**Pull request closed without merging**
