### PR TITLE
Fix CJK Ideographs and Hangul Syllables representation

### PR DESCRIPTION
**Pull request by GrabYourPitchforks**
Characters in these blocks weren't correctly identified as assigned characters, which caused the encoders to always encode them, even if the ranges were in the allow list.

Fixes https://github.com/aspnet/HttpAbstractions/issues/242.

### CODE REVIEW

**Comment by Eilon** [comment]
Looks :shipit: to me. Having that generator seems quite handy :smile: 

@GrabYourPitchforks do you want to merge yourself or shall I?

**Comment by GrabYourPitchforks** [comment]
I'll take it - was just waiting for signoff. Didn't want to rush it since everybody's heads-down right now. :)

**Comment by Eilon** [comment]
Okie dokie, please merge at your convenience!

**Comment by Eilon** [comment]
Thanks!

**Comment by davidfowl** [comment]
Can we make sure this doesn't break mono?

**Pull request merged**
