### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by smarts**
…to use non-class-specific language since the class-specific language resulted in problems when copying/pasting documentation between classes.

### CODE REVIEW

**Comment by Tratcher** [comment]
Good catch. We would prefer to use the (correct) type references in the doc comments though.

**Comment by jkotalik** [comment]
If you could change `<see cref="HeaderDictionary" />` to `<see cref="QueryCollection" />, that would be better.

**Comment by smarts** [comment]
sorry, this slipped off my radar. i'll try to get to it today

**Comment by muratg** [comment]
Thanks @smarts!

**Comment by smarts** [comment]
done @jkotalik  @muratg @Tratcher . not sure what went wrong w/ the build

**Comment by Tratcher** [comment]
The changes look good but it's on the wrong branch, it needs to go to the dev branch. Can you get that fixed? If not then @jkotalik can move it over.

**Pull request closed without merging**
