### PR TITLE
Faster StartsWithSegments Ordinal check

### PR DESCRIPTION
**Pull request by benaadams**
Framework's call to native comes with a cost

Before
string-startswith-before

After
string-startswith-after

### CODE REVIEW

**Comment by benaadams** [comment]
As an aside; the sets and whatnot have high costs as they are also doing dictionary lookups; typecasts and initalizing the feature cache

**Comment by halter73** [comment]
:shipit:

Do you have any thoughts @Tratcher?

**Comment by davidfowl** [comment]
Not a fan of this. Looks pretty unmaintainable. Is it really worth it? Can we make a change like this in corefx instead?

**Comment by benaadams** [comment]
Would be change to coreclr https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.cs#L2562

Will propose.

**Comment by halter73** [comment]
@davidfowl No less maintainable than `GetAsciiString` :stuck_out_tongue:

I see your point though. This is something probably done once per request at most, and I doubt most apps are going to specify `StringComparison.Ordinal`.

**Comment by benaadams** [comment]
@halter73 The crazy is currently localized to one project :)

**Comment by benaadams** [comment]
Raised PR in coreclr https://github.com/dotnet/coreclr/pull/2667

**Pull request closed without merging**
