### PR TITLE
Update WebEncoders from Unicode 7.0 to Unicode 8.0

### PR DESCRIPTION
**Pull request by GrabYourPitchforks**
Add "how to update" file detailing update steps
Addresses https://github.com/aspnet/HttpAbstractions/issues/387

/cc @ellismg and @KrzysztofCwalina since they were also looking at the encoder implementations

### CODE REVIEW

**Comment by muratg** [comment]
Thanks @GrabYourPitchforks!  @Tratcher could you have a look?

**Comment by KrzysztofCwalina** [comment]
Looks good. Thanks for doing the update.

**Comment by davidfowl** [comment]
@GrabYourPitchforks did you sign the new CLA?

**Comment by muratg** [comment]
@KrzysztofCwalina Will you pull this one into System.Text.Encoding.Web?

**Comment by KrzysztofCwalina** [comment]
@muratg, I will, unless you'd like to help out?

**Pull request merged**
