### PR TITLE
Remove IsLocal

### PR DESCRIPTION
**Pull request by BrennanConroy**
#536
@Tratcher 

Will need to update a couple repos when this goes in

### CODE REVIEW

**Comment by Tratcher** [comment]
:shipit: Check Hosting, WebListener, Kestrel, and BasicMiddleware.

**Comment by davidfowl** [comment]
:shipit:

**Comment by davidfowl** [comment]
Related to this idea, should we move IsHttps to an extension method?

**Comment by Tratcher** [comment]
@davidfowl *shrug*. Last chance if you're going to, but it's not a priority.

**Comment by davidfowl** [comment]
The weird thing about it not being a computed property is that the actual scheme and IsHttps can be out of sync. I'm not aware of that being an intentional design choice.

**Comment by Tratcher** [comment]
Well, it is actually computed: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http/DefaultHttpRequest.cs#L98-L102, but I guess that's not a guaranteed implementation detail.

**Comment by brockallen** [comment]
I'd very much like the `IsHttps` property to be kept. My $0.02.

**Comment by davidfowl** [comment]
Might make sense to make these things all computed and not settable.

**Comment by BrennanConroy** [comment]
:up: :date: Removed ```IsLocal``` from `IHttpConnectionFeature`

**Comment by Tratcher** [comment]
:shipit:

**Pull request merged**
