### PR TITLE
Refactor Encoders into their own package

### PR DESCRIPTION
**Pull request by GrabYourPitchforks**
Better refactoring per https://github.com/aspnet/HttpAbstractions/issues/193

### CODE REVIEW

**Comment by Eilon** [comment]
I approve this message :shipit:

**Comment by davidfowl** [comment]
What about Microsoft.AspNet.Encoders

**Comment by Eilon** [comment]
I'm kind of a fan of the original longer name, though I admit I can't think of what other kind of encoders we'd ever have that wouldn't be "web utilities." Then again, these encoders *are* web utilities...

**Comment by GrabYourPitchforks** [comment]
If they're in the AspNet namespace instead of the Framework namespace, that would imply web, no?

**Comment by davidfowl** [comment]
That's an interesting one. Microsoft.Framework.WebEncoders?

**Comment by Eilon** [comment]
`Microsoft.Framework.WebEncoders` --> that's not bad either. This really has nothing to do with ASP.NET does it? (ASP.NET = server web apps)

**Comment by GrabYourPitchforks** [comment]
WebEncoders works. Leave it in the HttpAbstractions repo for simplicity?

**Comment by davidfowl** [comment]
Leave it there for now.

**Comment by GrabYourPitchforks** [comment]
The most recent commit has the new names.

**Pull request merged**
