### PR TITLE
Swap Http and Http.Core package names. Remove Http.Core namespace

### PR DESCRIPTION
**Pull request by Tratcher**
#190 @davidfowl @muratg

### CODE REVIEW

**Comment by davidfowl** [comment]
:shipit:  @Tratcher I assume you're going to do a sweep and very other repository's dependencies.

**Comment by Tratcher** [comment]
Yes I'll push this through all the other repos when I push this in. The CI will hate me for an hour or two and then it will be over.

**Comment by davidfowl** [comment]
Seems like this needs rebase

**Comment by Tratcher** [comment]
I'd like to get the ConnectionInfo PR in first.

**Pull request merged**
