### PR TITLE
Move the header extensions to Http.Abstractions

### PR DESCRIPTION
**Pull request by davidfowl**
#489

/cc @Tratcher @muratg

### CODE REVIEW

**Comment by khellang** [comment]
No csproj changes! Oh, how I :heart: this :grin:

**Comment by davidfowl** [comment]
:golf: :clap:

**Comment by Tratcher** [comment]
Why these and not any of the other extensions? They aren't abstractions, they're just convenience methods.

**Comment by Tratcher** [comment]
If you think these are core functionality then put them directly on the interface.

**Comment by davidfowl** [comment]
Nah. The interface should have whatever is minimally required to implement it. These are extensions that work on top of *any*  implementation.

The bug is specifically about header extensions, also these don't bring in any other dependencies so easy to move.

**Pull request merged**
