### PR TITLE
String performance improvements on top of #411

### PR DESCRIPTION
**Pull request by NickCraver**
This adds additional performance improvements (namely string.Concat overloads) for a few cases. It also eliminates an extra check inside QueryHelper.

### CODE REVIEW

**Comment by davidfowl** [comment]
W00p!

**Comment by Tratcher** [comment]
As this is performance related, please share your relevant measurements.

**Comment by NickCraver** [comment]
@Tratcher sorry! I took for granted this was a more widely known thing - `string.Concat()` has overloads for up to 4 strings and it's substantially faster than `string.Format()` for these cases. I've put up some quick benchmarks here as a sample: https://gist.github.com/NickCraver/fce9754c50aa7a4c9593

**Comment by halter73** [comment]
:shipit:

**Comment by benaadams** [comment]
> string.Concat() has overloads for up to 4 strings and it's substantially faster than string.Format() for these cases.

Can't disagree; but feels like coreclr or rosyln is missing a trick here; or maybe its that they aren't missing the trick with `.Concat` :D

**Comment by khellang** [comment]
Is there an existing issue for optimizing these types of interpolated strings (basically concatenating strings) in the Roslyn repo?

**Pull request merged**
