### PR TITLE
[WIP] Add lazy features support and use for Forms and Cookies

### PR DESCRIPTION
**Pull request by pakrym**
@Tratcher @davidfowl

### CODE REVIEW

**Comment by Tratcher** [comment]
Hmm, so we have to re-write Kestrel and WebListener's feature collections to implement this? :-1:

**Comment by pakrym** [comment]
It does fallback to old style collection and implementation is not hard.

**Comment by rynowak** [comment]
Is this just an optimization for the case when those features are never created? For instance right now it's relatively expensive when the feature collection **versions**. If this means that accessing the form feature and query feature will bump the feature collection up to version 3, this is concerning.

**Comment by Tratcher** [comment]
Care to demonstrate the changes on Kestrel?

**Comment by pakrym** [comment]
@Tratcher rough implementation in https://github.com/aspnet/KestrelHttpServer/compare/pakrym/lazy-features

**Comment by pakrym** [comment]
@rynowak yes, this can be an issue.

**Comment by pakrym** [comment]
@rynowak Lazy initialization of value should not change Revision, only SetLazy should.

**Comment by Tratcher** [comment]
That makes the Frame class 2-3x as large as before, so isn't it a net loss for memory consumption?

**Comment by Tratcher** [comment]
@benaadams

**Comment by Tratcher** [comment]
@halter73

**Comment by pakrym** [comment]
Frame is per connection, and we can fine tune which features are stored lazily.

**Comment by davidfowl** [comment]
Not a fan of this new interface, seems to specialized.  The IFeatureCollection itself is already lazy.

**Comment by halter73** [comment]
@davidfowl I told @pakrym we should just make DefaultHttpContext implement IResponseCookiesFeature and IFormFeature. 0 allocations and no new interface :trollface:

**Comment by benaadams** [comment]
> Not a fan of this new interface, seems to specialized. The IFeatureCollection itself is already lazy.

DI feature collection with some lambda pre-compilation for injection resolution for features and services?
 
Or
```csharp
IFeatureCollection.Set<TFeature>();
IFeatureCollection.Set<TFeature>(TFeature instance);
IFeatureCollection.Set<TFeature>(Func<TFeature> implementationFactory);
IFeatureCollection.Set<TFeature>(Func<IFeatureCollection, TFeature> collectionFactory);
IFeatureCollection.Set<TFeature, TState>(Func<TState, TFeature> injectionFactory);
IFeatureCollection.Set<TFeature, TState>(Func<TState, TFeature> stateFactory, TState state);
```

**Comment by pakrym** [comment]
@davidfowl any ideas how can we avoid creating new interface and keep this functionality?

**Comment by benaadams** [comment]
The state could be curried/closure captured into the factories as its always the same? 
e.g.
```csharp
    public class HttpContextFactory : IHttpContextFactory
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private static readonly Func<IFeatureCollection, IResponseCookiesFeature> _responseCookiesFeatureFactory;
        private static readonly Func<HttpRequest, IFormFeature> _formFeatureFactory;

        public HttpContextFactory(ObjectPoolProvider poolProvider, IOptions<FormOptions> formOptions, IHttpContextAccessor httpContextAccessor)
        {
            if (poolProvider == null)
            {
                throw new ArgumentNullException(nameof(poolProvider));
            }
            if (formOptions == null)
            {
                throw new ArgumentNullException(nameof(formOptions));
            }

            var builderPool = poolProvider.CreateStringBuilderPool();
            var options = formOptions.Value;

            _responseCookiesFeatureFactory = (features) => {
                return new ResponseCookiesFeature(features, builderPool);
            };
            _formFeatureFactory = (request) => {
                return new FormFeature(request, options);
            };

            _httpContextAccessor = httpContextAccessor;
        }
```

**Comment by benaadams** [comment]
Capturing the state doesn't solve, chaining from the FeatureCollection with state, as it doesn't exist in the feature collection yet :(

**Pull request closed without merging**
