### PR TITLE
Make cookies return null when the key doesn't exist.

### PR DESCRIPTION
**Pull request by Kagamine**
We used to `if (Cookies["xxx"] == null)` to detect the key exist or not. 

Now, if key `xxx` doesn't exist, it will return "".

The String.Empty will equals to "", We have to use Cookies.Keys.Contains("xxx") to detect the key exist or not. it's so complex.

/cc @Eilon @troydai @JunTaoLuo

### CODE REVIEW

**Comment by Kagamine** [comment]
Should I add an Assert into public void Cookies_GetAndSet()?

```
Assert.IsNull(cookies1["name2"]);
```

**Comment by NickCraver** [comment]
+1 on this change, missing should be null. I think Headers should behave this way as well. It's going to be a porting painpoint. For example, with Headers I have to use `Microsoft.Extensions.Primitives` to do a `!= StringValues.Empty` check...that's just weird. Can we just keep it simple here?

I assume there was discussion and reasoning behind this change in the first place though, looking forward to hearing the background.

**Comment by davidfowl** [comment]
@NickCraver https://github.com/aspnet/Announcements/issues/60

**Comment by NickCraver** [comment]
@davidfowl I don't see the not-there case really well thought out there. Compare old vs. new code.
Old:
```C#
if (Request.Headers["MyHeader"] != null)
```
New:
```C#
if (!StringValues.IsNullOrEmpty(Request.Headers["MyHeader"]))
```
There may be an extension method I can't find as well? If it's there, it would require a `using` though - so many probably wouldn't find it.

I think it's pretty hard to argue that it's an intuitive change - I'm just not seeing the wins here for the missing case. IMO, `null` is a better return. With `?.` and `??`, it's an even bigger win.

**Comment by davidfowl** [comment]
We could add an extension method actually that's not a bad idea but it's a struct so null won't cut it.

**Comment by NickCraver** [comment]
True - I'd suggest the extension method be where intellisense will find it though, which would mean in already-used namespaces. IMO there's an argument to be made for pulling such basic types lower.

In this case might I suggest a `public bool IsEmpty => Count == 0;` (or possibly a different name) on `StringValues`? Eliminating the namespace navigation issues would be a good win here.

**Comment by benaadams** [comment]
Use `TryGet`? Or are you just testing it exists and don't care about its value?

**Comment by benaadams** [comment]
@NickCraver  surely

Old:
```csharp
if (Request.Headers["MyHeader"] != null)
```
New:
```csharp
if (Request.Headers.ContainsKey("MyHeader"))
```

Or:
```csharp
if (Request.Headers.TryGet("MyHeader", out header))
```

**Comment by benaadams** [comment]
@Kagamine rather than:
`if (Cookies["xxx"] == null)`
Try
`if (Cookies.ContainsKey("xxx"))`
Or if you want the value?
`if (Cookies.TryGet("xxx", out cookie))`

**Comment by Kagamine** [comment]
But in my computer, there was no ContainsKey with cookies.
I'm using the latest rc2.

**Comment by NickCraver** [comment]
@benaadams We often check for existence then default in such scenarios, I suppose the new format would be:
```C#
StringValues s;
var guid = Request.Headers.TryGetValue("Proxy-Guid", out s) ? s[0] : UnauthorizedGuid;
```
Where as before we're talking about:
```C#
var guid = Request.Headers["Proxy-Guid"] ?? UnauthorizedGuid;
```

I see the wins on the allocation side, but it hurts on the usability is all I'm noting - you convinced me it's an overall good change here. IMO, it's an overall win since we're after the maximum performance ultimately as well. 

Semi-related: It would be *really* nice if the headers were ordered, since while the RFC (2616 - 4.2) says the overall key ordering doesn't matter (though individual values do) - it does matter practically. For example, we can detect a botnet faking a browser based on header order - since we know Chrome sends headers in a certain order. However, I am a practical person - I see how this wouldn't matter for 99.9999% of websites :) I'm just noting such things here that probably aren't considered in the discussions but are hit in production...or I'm totally wrong and things like this are brought up in the meetings.

For cookies though (this PR), I think a `null` return is still more sane - we're getting no wins with the `string.Empty` return, only having to call `.IsNullOrEmpty()` or `!= ""` with no gains really.

**Comment by Kagamine** [comment]
In convention we used to Request.Headers["Proxy-Guid"] == null, not Request.Headers.ContainsKey

**Comment by Kagamine** [comment]
+1 missing should be null

**Comment by Tratcher** [comment]
The cookies and headers issues are quite different due to the different data types being used, please open a separate bug to discuss handling missing headers.

**Comment by Tratcher** [comment]
@Kagamine Yes this needs tests.

**Comment by Tratcher** [comment]
@Kagamine nevermind, I'm taking care of it as part of https://github.com/aspnet/HttpAbstractions/pull/463

**Pull request closed without merging**
