### PR TITLE
let UriHelper.GetEncodedUrl  can  get relative url

### PR DESCRIPTION
**Pull request by John0King**

### CODE REVIEW

**Comment by Tratcher** [comment]
This should be a separate method with a more specific name. GetEncodedPathAndQuery

**Comment by Tratcher** [comment]
@sebastienros is this what you were asking for? https://github.com/aspnet/Mvc/issues/5660

**Comment by sebastienros** [comment]
Yes. I am not sure what `BuildRelative` does to the concatenated string though.

**Comment by Tratcher** [comment]
BuildRelative just gives you intellisense for what values to concatenate.

**Pull request merged**
