### PR TITLE
[NoMerge] React to StringValues

### PR DESCRIPTION
**Pull request by benaadams**
Isn't it only `HeaderDictionary` that needs the change to not add `null`s to the dictionary in the `IDictionary` path as it does in the `IHeaderDictionary` path?

Also needs https://github.com/aspnet/Common/pull/330

/cc @Tratcher  @ryanbrandenburg @dougbu @rynowak @halter73

### CODE REVIEW

**Comment by benaadams** [comment]
e.g. currently its saying there is a header; then returning `null`; whereas it should say there isn't a header

**Comment by ryanbrandenburg** [comment]
Looks like the tests fail with this change.

**Comment by benaadams** [comment]
> Looks like the tests fail with this change.

Also needs aspnet/Common#330

**Comment by benaadams** [comment]
I can put a fix in (e.g. put `.ToArray();` back), then revert after?

**Comment by benaadams** [comment]
Added fix back

**Comment by Tratcher** [comment]
Heads up, the original change was reverted. We'll reintroduce it more cautiously by doing full universe builds before merging.

**Comment by muratg** [comment]
We’re closing this PR because we don’t feel that this change is a good fit for the product at this time. 

We thank you for the contribution and look forward to collaborating more in the future.

**Pull request closed without merging**
