### PR TITLE
Inlinable Fetch

### LINKED ISSUE #617: Should Fetch be made more inline-friendly?
It's common in MVC to see traces like:
image

There's about 1.33% of a request's time spent just doing the initial feature access. 

We should probably see what the JIT has to say about this code path and try to either optimize for:
- first read (`cached == null`) **OR**
- multiple reads (`cached != null && Revision == collection.Revision`)

by breaking this up into an inlinable fast path and non-inlinable slow path

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Features/FeatureReferences.cs#L26

### PR DESCRIPTION
**Pull request by benaadams**
Inlines `HttpResponse.Body`, `HttpResponse.Headers`, etc callchain when cached feature.

-----
**First Phase**

Shrunk `Fetch` made `UpdateCached` bigger by pushing some logic there. 

`Fetch` is called x4 of `UpdateCached` so that's a win.

Reduced Fetch to 59 il bytes which unfortunately is still too big for its depth in the call chain for the jit to think its profitable (though not too many il bytes)

So... `AggressiveInlining`d the rest...

Pre (with Fetch)

pre-fetch

Post (with Fetch inlined)

post-fetch

-----

**Second Phase**

The `[profitable inline] MulticastDelegate:CtorClosed(ref,long):this` was the inline lambda; so moved them to a readonly static, then the inlines went crazy! Seemed it was a blocker of sorts.

Now even `DefaultHttpResponse.HttpResponseFeature` gets inlined so have to go up a level to see the inlines.

Pre-fetch
pre-fetch

Post-fetch
pre-fetch

----

Resolves  #617

/cc @rynowak @Tratcher @davidfowl

### CODE REVIEW

**Comment by benaadams** [comment]
Pre

DefaultHttpResponse.HttpResponseFeature
```
Successfully inlined MulticastDelegate:CtorClosed(ref,long):this (24 IL bytes) (depth 1) [profitable inline]
Successfully inlined FeatureReferences``1:Fetch(byref,ref):ref:this (15 IL bytes) (depth 1) [below ALWAYS_INLINE size]
Successfully inlined FeatureReferences``1:get_Collection():ref:this (7 IL bytes) (depth 2) [below ALWAYS_INLINE size]
**************** Inline Tree
Inlines into 060000A4 DefaultHttpResponse:get_HttpResponseFeature():ref:this
  [1 IL=0042 TR=000080 060038F5] [profitable inline] MulticastDelegate:CtorClosed(ref,long):this
    [0 IL=0004 TR=000126 060038F4] [FAILED: does not return] MulticastDelegate:ThrowNullThisInDelegateToInstance():this
  [2 IL=0053 TR=000055 06000050] [below ALWAYS_INLINE size] FeatureReferences`1:Fetch(byref,ref):ref:this
    [3 IL=0003 TR=000134 0600004A] [below ALWAYS_INLINE size] FeatureReferences`1:get_Collection():ref:this
    [0 IL=0009 TR=000137 0600004E] [FAILED: unprofitable inline] FeatureReferences`1:Fetch(byref,ref,ref):ref:this
Budget: initialTime=237, finalTime=287, initialBudget=2370, currentBudget=2370
Budget: initialSize=1476, finalSize=1647
```
FeatureReferences.Fetch
```
Successfully inlined FeatureReferences``1:get_Collection():ref:this (7 IL bytes) (depth 1) [below ALWAYS_INLINE size]
Successfully inlined FeatureReferences``1:get_Revision():int:this (7 IL bytes) (depth 1) [below ALWAYS_INLINE size]
Successfully inlined FeatureReferences``1:set_Revision(int):this (8 IL bytes) (depth 1) [below ALWAYS_INLINE size]
**************** Inline Tree
Inlines into 0600004E FeatureReferences`1:Fetch(byref,ref,ref):ref:this
  [1 IL=0001 TR=000002 0600004A] [below ALWAYS_INLINE size] FeatureReferences`1:get_Collection():ref:this
  [0 IL=0006 TR=000005 06000052] [FAILED: target not direct] IFeatureCollection:get_Revision():int:this
  [2 IL=0013 TR=000010 0600004C] [below ALWAYS_INLINE size] FeatureReferences`1:get_Revision():int:this
  [0 IL=0040 TR=000096 0600004F] [FAILED: unprofitable inline] FeatureReferences`1:UpdateCached(byref,ref,ref):ref:this
  [3 IL=0060 TR=000028 0600004D] [below ALWAYS_INLINE size] FeatureReferences`1:set_Revision(int):this
  [0 IL=0069 TR=000035 0600004F] [FAILED: unprofitable inline] FeatureReferences`1:UpdateCached(byref,ref,ref):ref:this
Budget: initialTime=285, finalTime=287, initialBudget=2850, currentBudget=2850
Budget: initialSize=1841, finalSize=1841
Successfully inlined FeatureReferences`1:get_Collection():ref:this (7 IL bytes) (depth 1) [below ALWAYS_INLINE size]
Successfully inlined FeatureReferences`1:get_Collection():ref:this (7 IL bytes) (depth 1) [below ALWAYS_INLINE size]
Successfully inlined FeatureReferences`1:get_Collection():ref:this (7 IL bytes) (depth 1) [below ALWAYS_INLINE size]
Successfully inlined FeatureReferences`1:set_Revision(int):this (8 IL bytes) (depth 1) [below ALWAYS_INLINE size]
```
Post

DefaultHttpResponse.HttpResponseFeature
```
Successfully inlined MulticastDelegate:CtorClosed(ref,long):this (24 IL bytes) (depth 1) [profitable inline]
Successfully inlined FeatureReferences``1:Fetch(byref,ref):ref:this (15 IL bytes) (depth 1) [below ALWAYS_INLINE size]
Successfully inlined FeatureReferences``1:get_Collection():ref:this (7 IL bytes) (depth 2) [below ALWAYS_INLINE size]
Successfully inlined FeatureReferences``1:Fetch(byref,ref,ref):ref:this (59 IL bytes) (depth 2) [aggressive inline attribute]
Successfully inlined FeatureReferences``1:get_Collection():ref:this (7 IL bytes) (depth 3) [below ALWAYS_INLINE size]
Successfully inlined FeatureReferences``1:get_Revision():int:this (7 IL bytes) (depth 3) [below ALWAYS_INLINE size]
**************** Inline Tree
Inlines into 060000A4 DefaultHttpResponse:get_HttpResponseFeature():ref:this
  [1 IL=0042 TR=000080 060038F5] [profitable inline] MulticastDelegate:CtorClosed(ref,long):this
    [0 IL=0004 TR=000126 060038F4] [FAILED: does not return] MulticastDelegate:ThrowNullThisInDelegateToInstance():this
  [2 IL=0053 TR=000055 06000050] [below ALWAYS_INLINE size] FeatureReferences`1:Fetch(byref,ref):ref:this
    [3 IL=0003 TR=000134 0600004A] [below ALWAYS_INLINE size] FeatureReferences`1:get_Collection():ref:this
    [4 IL=0009 TR=000137 0600004E] [aggressive inline attribute] FeatureReferences`1:Fetch(byref,ref,ref):ref:this
      [5 IL=0003 TR=000154 0600004A] [below ALWAYS_INLINE size] FeatureReferences`1:get_Collection():ref:this
      [0 IL=0008 TR=000157 06000052] [FAILED: target not direct] IFeatureCollection:get_Revision():int:this
      [6 IL=0015 TR=000162 0600004C] [below ALWAYS_INLINE size] FeatureReferences`1:get_Revision():int:this
      [0 IL=0053 TR=000193 0600004F] [FAILED: too many il bytes] FeatureReferences`1:UpdateCached(byref,ref,ref,int,bool):ref:this
Budget: initialTime=237, finalTime=391, initialBudget=2370, currentBudget=2370
Budget: discretionary inline caused a force inline
Budget: initialSize=1476, finalSize=1647
```

**Comment by benaadams** [comment]
Update:

The `[profitable inline] MulticastDelegate:CtorClosed(ref,long):this` was the inline lambda; so moved them to a readonly static, then the inlines went crazy! 

Pre-fetch
pre-fetch

Post-fetch
pre-fetch

@rynowak inlined enough for you? :wink:

**Comment by davidfowl** [comment]
That's huge! This is awesome!

**Comment by benaadams** [comment]
So now even `DefaultHttpResponse.HttpResponseFeature` gets inlined so have to go up a level to see the inlines

Post 

DefaultHttpResponse:get_Body

```
Successfully inlined DefaultHttpResponse:get_HttpResponseFeature():ref:this (33 IL bytes) (depth 1) [profitable inline]
Successfully inlined FeatureReferences`1:Fetch(byref,ref):ref:this (15 IL bytes) (depth 2) [below ALWAYS_INLINE size]
Successfully inlined FeatureReferences`1:get_Collection():ref:this (7 IL bytes) (depth 3) [below ALWAYS_INLINE size]
Successfully inlined FeatureReferences`1:Fetch(byref,ref,ref):ref:this (59 IL bytes) (depth 3) [aggressive inline attribute]
Successfully inlined FeatureReferences`1:get_Collection():ref:this (7 IL bytes) (depth 4) [below ALWAYS_INLINE size]
Successfully inlined FeatureReferences`1:get_Revision():int:this (7 IL bytes) (depth 4) [below ALWAYS_INLINE size]
**************** Inline Tree
Inlines into 060000AA DefaultHttpResponse:get_Body():ref:this
  [1 IL=0001 TR=000002 060000A4] [profitable inline] DefaultHttpResponse:get_HttpResponseFeature():ref:this
    [2 IL=0027 TR=000019 06000050] [below ALWAYS_INLINE size] FeatureReferences`1:Fetch(byref,ref):ref:this
      [3 IL=0003 TR=000031 0600004A] [below ALWAYS_INLINE size] FeatureReferences`1:get_Collection():ref:this
      [4 IL=0009 TR=000035 0600004E] [aggressive inline attribute] FeatureReferences`1:Fetch(byref,ref,ref):ref:this
        [5 IL=0003 TR=000061 0600004A] [below ALWAYS_INLINE size] FeatureReferences`1:get_Collection():ref:this
        [0 IL=0008 TR=000064 06000052] [FAILED: target not direct] IFeatureCollection:get_Revision():int:this
        [6 IL=0015 TR=000069 0600004C] [below ALWAYS_INLINE size] FeatureReferences`1:get_Revision():int:this
        [0 IL=0053 TR=000100 0600004F] [FAILED: noinline per IL/cached result] FeatureReferences`1:UpdateCached(byref,ref,ref,int,bool):ref:this
  [0 IL=0006 TR=000005 06000085] [FAILED: target not direct] IHttpResponseFeature:get_Body():ref:this
Budget: initialTime=96, finalTime=268, initialBudget=960, currentBudget=960
Budget: discretionary inline caused a force inline
Budget: initialSize=404, finalSize=664
```

DefaultHttpResponse:get_Headers

```
Successfully inlined DefaultHttpResponse:get_HttpResponseFeature():ref:this (33 IL bytes) (depth 1) [profitable inline]
Successfully inlined FeatureReferences`1:Fetch(byref,ref):ref:this (15 IL bytes) (depth 2) [below ALWAYS_INLINE size]
Successfully inlined FeatureReferences`1:get_Collection():ref:this (7 IL bytes) (depth 3) [below ALWAYS_INLINE size]
Successfully inlined FeatureReferences`1:Fetch(byref,ref,ref):ref:this (59 IL bytes) (depth 3) [aggressive inline attribute]
Successfully inlined FeatureReferences`1:get_Collection():ref:this (7 IL bytes) (depth 4) [below ALWAYS_INLINE size]
Successfully inlined FeatureReferences`1:get_Revision():int:this (7 IL bytes) (depth 4) [below ALWAYS_INLINE size]
**************** Inline Tree
Inlines into 060000A9 DefaultHttpResponse:get_Headers():ref:this
  [1 IL=0001 TR=000002 060000A4] [profitable inline] DefaultHttpResponse:get_HttpResponseFeature():ref:this
    [2 IL=0027 TR=000019 06000050] [below ALWAYS_INLINE size] FeatureReferences`1:Fetch(byref,ref):ref:this
      [3 IL=0003 TR=000031 0600004A] [below ALWAYS_INLINE size] FeatureReferences`1:get_Collection():ref:this
      [4 IL=0009 TR=000035 0600004E] [aggressive inline attribute] FeatureReferences`1:Fetch(byref,ref,ref):ref:this
        [5 IL=0003 TR=000061 0600004A] [below ALWAYS_INLINE size] FeatureReferences`1:get_Collection():ref:this
        [0 IL=0008 TR=000064 06000052] [FAILED: target not direct] IFeatureCollection:get_Revision():int:this
        [6 IL=0015 TR=000069 0600004C] [below ALWAYS_INLINE size] FeatureReferences`1:get_Revision():int:this
        [0 IL=0053 TR=000100 0600004F] [FAILED: noinline per IL/cached result] FeatureReferences`1:UpdateCached(byref,ref,ref,int,bool):ref:this
  [0 IL=0006 TR=000005 06000083] [FAILED: target not direct] IHttpResponseFeature:get_Headers():ref:this
Budget: initialTime=96, finalTime=268, initialBudget=960, currentBudget=960
Budget: discretionary inline caused a force inline
Budget: initialSize=404, finalSize=664
```

**Comment by benaadams** [comment]
`_renamedTheDelegates`

**Comment by LetMeCodeThis** [comment]
Ohh dear Mr @benaadams! Love to look at yours PR's! Keep up the good work!

**Comment by rynowak** [comment]
@davidfowl told ya so :trollface: 

@benaadams :heart_eyes_cat: - this is great stuff

**Comment by rynowak** [comment]
Digging into the inlinability of this a bit more, I ended up here: https://github.com/dotnet/coreclr/blob/dbe69102224886888874b56f5e2c5b3905bd8fa2/src/mscorlib/src/System/MulticastDelegate.cs#L609

This seems like something we should bring up with CLR folks - I'm guessing this limitation with inlinability is known, but something about the codegen is triggering this case for even a non-capturing lambda.

**Comment by benaadams** [comment]
Well... what is said is true it does help with inlining; in that `CtorClosed` does get inlined. However it also then gets removed as I assume it would show up on memory traces otherwise - bit it still seems to cost against the inline budget (pushing this inline over the il bdget).

Perhaps the lambda cache/hoisting analysis happens after the inline analysis?

**Comment by rynowak** [comment]
AFAIK the *hoisting* of lambdas is a compiler feature and lambdas have no representation in IL.

**Comment by benaadams** [comment]
Interesting... That's just a bit weird then...

**Comment by benaadams** [comment]
So...

Before it inserts a lazy static init into the callsite
```cil
.method private hidebysig specialname instance class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IHttpResponseFeature 
        get_HttpResponseFeature() cil managed
{
  // Code size       59 (0x3b)
  .maxstack  8
  IL_0000:  ldarg.0
  IL_0001:  ldflda     valuetype [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.FeatureReferences`1<valuetype Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse/FeatureInterfaces> Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse::_features
  IL_0006:  ldarg.0
  IL_0007:  ldflda     valuetype [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.FeatureReferences`1<valuetype Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse/FeatureInterfaces> Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse::_features
  IL_000c:  ldflda     !0 valuetype [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.FeatureReferences`1<valuetype Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse/FeatureInterfaces>::Cache
  IL_0011:  ldflda     class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IHttpResponseFeature Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse/FeatureInterfaces::Response
  IL_0016:  ldsfld     class [System.Runtime]System.Func`2<class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IFeatureCollection,class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IHttpResponseFeature> Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse/'<>c'::'<>9__6_0'
  IL_001b:  dup
  IL_001c:  brtrue.s   IL_0035
  IL_001e:  pop
  IL_001f:  ldsfld     class Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse/'<>c' Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse/'<>c'::'<>9'
  IL_0024:  ldftn      instance class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IHttpResponseFeature Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse/'<>c'::'<get_HttpResponseFeature>b__6_0'(class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IFeatureCollection)
  IL_002a:  newobj     instance void class [System.Runtime]System.Func`2<class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IFeatureCollection,class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IHttpResponseFeature>::.ctor(object,
                                                                                                                                                                                                                                                                                   native int)
  IL_002f:  dup
  IL_0030:  stsfld     class [System.Runtime]System.Func`2<class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IFeatureCollection,class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IHttpResponseFeature> Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse/'<>c'::'<>9__6_0'
  IL_0035:  call       instance !!0 valuetype [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.FeatureReferences`1<valuetype Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse/FeatureInterfaces>::Fetch<class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IHttpResponseFeature>(!!0&,
                                                                                                                                                                                                                                                                                                                                       class [System.Runtime]System.Func`2<class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IFeatureCollection,!!0>)
  IL_003a:  ret
} // end of method DefaultHttpResponse::get_HttpResponseFeature
```

After the static init is in the static readonly, so it doesn't insert it into the call site
```cil
.method private hidebysig specialname instance class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IHttpResponseFeature 
        get_HttpResponseFeature() cil managed
{
  // Code size       33 (0x21)
  .maxstack  8
  IL_0000:  ldarg.0
  IL_0001:  ldflda     valuetype [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.FeatureReferences`1<valuetype Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse/FeatureInterfaces> Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse::_features
  IL_0006:  ldarg.0
  IL_0007:  ldflda     valuetype [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.FeatureReferences`1<valuetype Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse/FeatureInterfaces> Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse::_features
  IL_000c:  ldflda     !0 valuetype [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.FeatureReferences`1<valuetype Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse/FeatureInterfaces>::Cache
  IL_0011:  ldflda     class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IHttpResponseFeature Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse/FeatureInterfaces::Response
  IL_0016:  ldsfld     class [System.Runtime]System.Func`2<class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IFeatureCollection,class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IHttpResponseFeature> Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse::_nullResponseFeature
  IL_001b:  call       instance !!0 valuetype [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.FeatureReferences`1<valuetype Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse/FeatureInterfaces>::Fetch<class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IHttpResponseFeature>(!!0&,
                                                                                                                                                                                                                                                                                                                                       class [System.Runtime]System.Func`2<class [Microsoft.AspNetCore.Http.Features]Microsoft.AspNetCore.Http.Features.IFeatureCollection,!!0>)
  IL_0020:  ret
} // end of method DefaultHttpResponse::get_HttpResponseFeature
```

**Comment by benaadams** [comment]
Raised issue https://github.com/dotnet/roslyn/issues/13624

**Comment by cesarbs** [comment]
Again I'll ask for comments explaining the code is written the way it's written to favor inlining :grin:

**Comment by pakrym** [comment]
Do we need a test suite to verify that we don't regress these?

**Comment by benaadams** [comment]
@cesarbs added explans

**Comment by benaadams** [comment]
@pakrym not sure how would go about writing a test. I think coreclr have some jit tests of this nature; but they are beyond my skill at this time.

**Comment by cesarbs** [comment]
@benaadams Thanks for the thorough comments!

**Comment by benaadams** [comment]
Any changes needed?

**Pull request merged**
