### PR TITLE
Rename Microsoft.AspNet.HttpFeature to Microsoft.AspNet.Http.Interfaces

### PR DESCRIPTION
**Pull request by halter73**
If you want to know why, ask @davidfowl!

### CODE REVIEW

**Comment by Tratcher** [comment]
https://github.com/aspnet/HttpAbstractions/issues/150

**Comment by Tratcher** [comment]
I'd have much preferred Ms.AspNet.Http.Features or Features.Interfaces, but *shrug*

**Comment by davidfowl** [comment]
It's more consistent with the other package names :shipit:

**Comment by Eilon** [comment]
:shipit: from me too, though I won't ask @davidfowl why. If you need any assistance with the CI (as is often the case with renames), let me know.

**Comment by davidfowl** [comment]
too late :P and @tugberkugurlu agrees with me

**Pull request merged**
