### PR TITLE
Added HTTP Status codes from the RFCs 4918 and 7538

### PR DESCRIPTION
**Pull request by 0xdeafcafe**
These two RFCs are finalized, and rather useful that I feel we should have in the core framework.

[7538 RFC Spec](https://tools.ietf.org/html/rfc7538)
[4918 RFC Spec](https://tools.ietf.org/html/rfc4918)

### CODE REVIEW

**Comment by khellang** [comment]
Nice. Submitted 308 for Kestrel as well; https://github.com/aspnet/KestrelHttpServer/pull/925

**Comment by Tratcher** [comment]
308 should be fine.

Are you actually using WebDAV? Or are you just adding them for completeness?

**Comment by 0xdeafcafe** [comment]
I'm using the `unprocessable_entity` status code, as it's a good one to use if model validation fails, for instance.

I just added the entire RFC while I was at it for completeness sake. Currently I'm doing this, which I'd rather not (I know I could just extend StatusCodes myself, but I thought I'd just do a pull request instead):

``` csharp
if (!ModelState.IsValid)
	return Json(422 /* unprocessable_entity */, ModelState.ToDictionary());

var question = _lawsContext.Questions.FirstOrDefault(q => q.Id == questionId);
if (question == null)
	return Json(StatusCodes.Status404NotFound, new Error<object>("question_not_found"));

// Verify Module Id is real
var scope = _lawsContext.Scopes.FirstOrDefault(r => r.Id == (Guid) model.ScopeId);
if (scope == null)
	return Json(422 /* unprocessable_entity */, new Error<object>("scope_not_found"));
```

**Comment by Tratcher** [comment]
:shipit:

**Comment by Tratcher** [comment]
Rebased and merged. Thanks.

**Comment by xperiandri** [comment]
It would be also nice to have an `UnprocessableEntityObjectResult` class and `UnprocessableEntity()` method on `Controller`

**Pull request closed without merging**
