### PR TITLE
Reset fields on AuthenticateContext

### PR DESCRIPTION
**Pull request by rynowak**
This is needed for cases where IAuthenticationHandler instances delegate
or modify the output of each-other.

### CODE REVIEW

**Comment by Tratcher** [comment]
@HaoK do you think this is going to have any interesting side-effects?

**Comment by rynowak** [comment]
I think if we had any code that called multiple different of these methods already we would have found this :laughing: 

Claims transformer calls `Authenticated` again only if the context is already authenticated, which works in the existing code.

**Comment by HaoK** [comment]
Yeah this change seems fine, before we were not expecting these to be modified more than once, basically expectation was one of these methods is called and that's it...

**Comment by Tratcher** [comment]
:shipit:

**Comment by rynowak** [comment]
Ok cool, does someone want to stamp a :shipit: on here then?

**Comment by rynowak** [comment]
beat me to it :laughing:

**Pull request closed without merging**
